import fs from 'fs/promises';import path from 'path';import { createClient } from '@supabase/supabase-js';
const root=path.join(process.cwd(),'data');
export function supabase(){const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_KEY;if(!url||!key)return null;return createClient(url,key,{auth:{persistSession:false}})}
const toCourse=(r:any)=>({id:r.id,name:r.name,price:Number(r.price||0),duration:r.duration,modules:r.modules||[],description:r.description,image:r.image,sellerLink:r.seller_link,status:r.status,category:r.category||'main'});
const fromCourse=(x:any)=>({id:x.id,name:x.name,price:Number(x.price||0),duration:x.duration,modules:Array.isArray(x.modules)?x.modules:String(x.modules||'').split(',').map((s:string)=>s.trim()).filter(Boolean),description:x.description,image:x.image,seller_link:x.sellerLink||x.seller_link,status:x.status||'active',category:x.category||'main'});
const toService=(r:any)=>({id:r.id,title:r.title,description:r.description,startingPrice:Number(r.starting_price||0),features:r.features||[],portfolioImages:r.portfolio_images||[]});
const fromService=(x:any)=>({id:x.id,title:x.title,description:x.description,starting_price:Number(x.startingPrice||x.starting_price||0),features:Array.isArray(x.features)?x.features:String(x.features||'').split(',').map((s:string)=>s.trim()).filter(Boolean),portfolio_images:Array.isArray(x.portfolioImages)?x.portfolioImages:String(x.portfolioImages||'').split(',').map((s:string)=>s.trim()).filter(Boolean)});
const toLead=(r:any)=>({id:r.id,createdAt:r.created_at,name:r.name,businessName:r.business_name,phone:r.phone||r.whatsapp,email:r.email,serviceNeeded:r.service_needed||r.service,budget:r.budget,description:r.description||r.project_details,status:r.status,emailSent:r.email_sent,sheetSent:r.sheet_sent});
const fromLead=(x:any)=>({id:x.id,name:x.name,business_name:x.businessName||x.business_name,phone:x.phone,whatsapp:x.phone,email:x.email,service_needed:x.serviceNeeded||x.service_needed,service: String(x.serviceNeeded||x.service_needed||'Other').toLowerCase().includes('bot')?'AI Chatbot':String(x.serviceNeeded||x.service_needed||'').toLowerCase().includes('automat')?'Automation':String(x.serviceNeeded||x.service_needed||'').toLowerCase().includes('web')?'Website':'Other',budget:x.budget,description:x.description,project_details:x.description,status:x.status==='contacted'?'Contacted':x.status==='closed'?'Closed':'New'});
async function readLocal<T>(name:string,fallback:T):Promise<T>{try{return JSON.parse(await fs.readFile(path.join(root,name),'utf8'))}catch{return fallback}}
async function writeLocal<T>(name:string,data:T){await fs.mkdir(root,{recursive:true});await fs.writeFile(path.join(root,name),JSON.stringify(data,null,2));return data}
export async function readJson<T>(name:string,fallback:T):Promise<T>{const sb=supabase(); if(sb){try{if(name==='courses.json'){const{data,error}=await sb.from('courses').select('*').order('created_at',{ascending:true});if(!error&&data)return data.map(toCourse) as T} if(name==='services.json'){const{data,error}=await sb.from('services').select('*').order('created_at',{ascending:true});if(!error&&data)return data.map(toService) as T} if(name==='leads.json'){const{data,error}=await sb.from('leads').select('*').order('created_at',{ascending:false});if(!error&&data)return data.map(toLead) as T} if(name==='content.json'){const [faqs,tests,settings]=await Promise.all([sb.from('faqs').select('*').order('created_at',{ascending:true}),sb.from('testimonials').select('*').order('created_at',{ascending:true}),sb.from('site_settings').select('*').eq('id','main').single()]); if(!faqs.error&&!tests.error&&!settings.error){const s=settings.data||{};return {settings:{heroTitle:s.hero_title,heroSubtitle:s.hero_subtitle,momoNumber:s.momo_number,students:s.students,rating:s.rating},faqs:faqs.data,testimonials:tests.data,kbSources:s.kb_sources||[]} as T}}}catch{}}
 return readLocal(name,fallback)}
export async function writeJson<T>(name:string,data:any){const sb=supabase(); if(sb&&name==='content.json'){await sb.from('site_settings').upsert({id:'main',hero_title:data.settings?.heroTitle,hero_subtitle:data.settings?.heroSubtitle,momo_number:data.settings?.momoNumber,students:data.settings?.students,rating:data.settings?.rating,kb_sources:data.kbSources||[]}); const faqIds=(data.faqs||[]).map((x:any)=>x.id); const tIds=(data.testimonials||[]).map((x:any)=>x.id); if(faqIds.length) await sb.from('faqs').delete().not('id','in',`(${faqIds.join(',')})`); if(tIds.length) await sb.from('testimonials').delete().not('id','in',`(${tIds.join(',')})`); for(const f of data.faqs||[]) await sb.from('faqs').upsert(f); for(const t of data.testimonials||[]) await sb.from('testimonials').upsert(t);}
 return process.env.VERCEL?data:writeLocal(name,data)}
export async function upsertItem(name:string,item:any){const id=item.id||`${name.replace('.json','')}-${Date.now()}`;item={...item,id};const sb=supabase(); if(sb){if(name==='courses.json') await sb.from('courses').upsert(fromCourse(item)); if(name==='services.json') await sb.from('services').upsert(fromService(item)); if(name==='leads.json') await sb.from('leads').upsert(fromLead(item));}
 const items:any[]=await readLocal(name,[]);const idx=items.findIndex(x=>x.id===item.id); if(idx>=0)items[idx]=item; else items.unshift(item); if(process.env.VERCEL)return item; await writeLocal(name,items); return item}
export async function deleteItem(name:string,id:string){const sb=supabase(); if(sb){if(name==='courses.json') await sb.from('courses').delete().eq('id',id); if(name==='services.json') await sb.from('services').delete().eq('id',id); if(name==='leads.json') await sb.from('leads').delete().eq('id',id)}if(process.env.VERCEL)return {deleted:id};const items:any[]=await readLocal(name,[]);await writeLocal(name,items.filter(x=>x.id!==id));return {deleted:id}}
